### ISSUE TITLE
Realms file grows "infinitely" 

### ISSUE THREAD

**Issue by astatio** [realm/realm-kotlin#1007]
I have a realms file that grows "infinitely" (theoretically).
I update this file around 5 times a second and I get the latest version using a write transaction (doing the query outside a write transaction and then updating inside of it will throw an exception so this is the only way possible) and I always put each one of these write transactions inside a try-with-resources. 

The logic is looking up an ID and getting a long field and add a quantity to it everytime the function is triggered. 

The file grows immensity big and within a month the file grew to 23GB! When I open it with Realm Studio and export as a new realm file the resulting size is a mere 705KB - far more accurate when taking into account the small amount of data inside. I was unable to find anything in the documentation that could justify this behaviour but it's really bad to have a file grow this large unnecessarily. Why does this happen?

**Comment by cmelchior** [comment]
Hi @astatio 

Sorry for the late reply.

This normally happens due to something called "version pinning", which happens when you are holding a reference to an object while other writes are happening. Realm is an MVCC database, so we track all live versions of the Realm. You can read more about this here:  https://www.mongodb.com/docs/realm/sdk/swift/crud/threading/#realm-s-threading-model-in-depth

In Kotlin you can try to enable this setting https://www.mongodb.com/docs/realm-sdks/kotlin/1.0.2/library-base/-realm%20-kotlin%20-s-d-k/io.realm.kotlin/-configuration/max-number-of-active-versions.html which will catch it if this happens.

We are also in the process of making some internal changes, so the chance of this happening is much lower. See https://github.com/realm/realm-core/pull/5440

For now, if you hit this, you need to ensure that you are not holding on to objects for longer than you strictly need them. Perhaps copying their data in memory and releasing the object.

I hope that clarifies things.

**Comment by ganfra** [comment]
I have the same issue here. 
What do you mean in practice to "Perhaps copying their data in memory and releasing the object."
Is there a method we should call to release the object? Also when using frozen objects through flows, this should not be an issue because the object is not managed, right?

**Comment by astatio** [comment]
I would like to state that this was finally fixed with 1.6.0
Amazing!

**Comment by astatio** [comment]
Despite the bot reopening, i will close it as its fixed now.
