### ISSUE TITLE
Multiplatform build fails with "Caused by: java.lang.IllegalStateException: Cannot find io.realm.kotlin.types.RealmUUID on platform Native (general)."

### ISSUE THREAD

**Issue by DarkSatyr** [realm/realm-kotlin#1049]
Kotlin version: 212-1.7.10-release-333-AS5457.46
Realm: 1.2.0

Gradle file: https://pastebin.com/063xp4S9

**Comment by cmelchior** [comment]
The problem is that your version of the plugin doesn't match the dependencies. 

You have

```
    id("io.realm.kotlin")
```

Since you don't set the version here, I suspect it is being set by the top-level module. Most likely it is `1.2.0`, but your dependencies are `implementation("io.realm.kotlin:library-base:1.0.2")`

These two numbers need to match, otherwise you will see exceptions like the one you are getting.

**Comment by DarkSatyr** [comment]
yes, it was my bad with versions, thanks, man!
