### ISSUE TITLE
Bulk list insert performance

### ISSUE THREAD

**Issue by francescoceko** [realm/realm-kotlin#1127]
I'm doing some comparison between Java sdk and kotlin one. I see on the kotlin version a method to bulk insert elements is not available. 
I then found this a suggested way:

    suspend fun insert(list: List<RealmItemKotlin>) {
        realm.write {
            delete(query(RealmItemKotlin::class).find())
            list.map { copyToRealm(it) }
        }
    }
    
Now I did some performance tests and compared to the same java function to insert 100K element list, takes 3s in Java and 13s in Kotlin.
I'm maybe missing something here? or maybe a better way to do it?

Francesco

**Comment by cmelchior** [comment]
Hi @francescoceko 

No, that is currently the only way to do it.  Just out of curiosity, are you testing on JVM or on Android? Because we have discovered that we were shipping debug builds on JVM Linux and Mac which would affect performance (a fix is underway).

But this is also on our radar as we know some places that can be optimized to support cases like this.

This is already being tracked here: https://github.com/realm/realm-kotlin/issues/959, so I'll be folding this issue into that one.

**Comment by francescoceko** [comment]
I'm testing on Android.
