### ISSUE TITLE
RealmList remove method is not working.

### ISSUE THREAD

**Issue by ggajews** [realm/realm-kotlin#1477]
### How frequently does the bug occur?

Always

### Description

RealmList [remove](https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-base/io.realm.kotlin.types/-realm-list/index.html#731697687%2FFunctions%2F878332154) element is not removing.

To reproduce:
```kotlin
class Child : RealmObject {
    @PrimaryKey
    var id: Long = 0
}
class Parent : RealmObject {
    var children: RealmList<Child> = realmListOf()
}

realm.write {
            val parent = copyToRealm(Parent())
            parent.children.add(Child().apply { id = 1 })
            assertEquals(1, parent.children.size)
            parent.children.remove(parent.children.first())
            assertEquals(0, parent.children.size)
        }
```

### Can you reproduce the bug?

Always

### Version

1.10.1

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 13

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by cmelchior** [comment]
Hi @ggajews This is happening because the RealmObject equals method is not working correctly. See https://github.com/realm/realm-kotlin/issues/1097 ... It appears that this has crept through the cracks and should be fixed.

I'll fold this into #1097 

The workaround, for now, could be to either override the equals method yourself.
