### ISSUE TITLE
Flaky test: realmAsFlow_doesNotTrackVersions[macos] 

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#1558]
`
kotlin.AssertionError: VersionInfo(main=VersionData(current=null, active=[]), notifier=VersionData(current=VersionId(version=5), active=[]), writer=VersionData(current=VersionId(version=5), active=[])). Expected <1>, actual <0>.
`

From: https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-1510/12/tests

**Comment by rorbech** [comment]
This is fixed by https://github.com/realm/realm-kotlin/pull/1559/files#diff-8efcbfab65bc64c0569bfe6dc7b386397ffaf19fc36ffeb32ed464babed1b3a3R154. https://github.com/realm/realm-kotlin/pull/1519 reworked tracking the initial version in the _user facing_ realm which might be released by the GC at a later stage.
