### ISSUE TITLE
PATCH requests timeout on Native (macOS)

### ISSUE THREAD

**Issue by edualonso** [realm/realm-kotlin#519]

**Comment by cmelchior** [comment]
I have been running into this in https://github.com/realm/realm-kotlin/pull/759, but found a workaround in https://stackoverflow.com/questions/69935799/ktor-client-unit-test-hangs-freezes-within-coroutinescope-launch#comment123688694_69935799

The root cause still escapes me though. Maybe we are hitting multiple different subtle bugs.

**Comment by cmelchior** [comment]
The above fix didn't work after some more testing. On the positive side, then I found the root cause https://youtrack.jetbrains.com/issue/KTOR-4101.

Unfortunately, it was already reported last year, but fixing it doesn't seem to be a priority.

Since we are only using PATCH requests in our Admin API I think we can implement a work-around that uses our test webserver as a forwarding proxy. I.e. we we package all the metadata for the request into a POST message we can send to our command server, then it is responsible for constructing the PATCH request, send it, receive the result and pass it back.

**Comment by cmelchior** [comment]
The alternative would be to create a platform abstraction that uses whatever HTTP is available on each platform, but implementing a URLConnection on Android/JVM seems rather annoying + I don't even know how to do it on macOS/iOS.
