### ISSUE TITLE
how fast is Realm.open()

### ISSUE THREAD

**Issue by shalva97** [realm/realm-kotlin#550]
what is the performance cost of Realm.open()? just curious, what if I want to create hundreds or thousands of realm instances.

**Comment by cmelchior** [comment]
I assume you mean different Realm files? We haven't benchmarked it yet, but It is a relatively heavyweight operation. We need to memory-map the underlying file, parse and validate the schema and create internal classes. So probably anything from 10-50 ms depending on the hardware and numbers I have seen from Realm Java

Creating a single Realm is probably fast enough to happen on the UI thread, especially since it only needs to happen once, creating 10-100's of Realms is going to take time, so I would do that on a background thread. But it is possible.

With 1000's of Realms you will probably run out of file descriptors...  I believe Android allows 1024 and a local  Realm uses 4, while a synchronized Realm uses 6 (or something close to it).

But what would the use-case be for having so many open Realms at the same time?

**Comment by shalva97** [comment]
There is so many posts about DI and Clean Architecture and separating logic between different modules.... Decided  to do it all backwards.

Every object will have everything they need or they will create their own dependencies.
For example, I have a browser app, there will be Tab class. All tabs that will be created will call Realm.open() to save themselves in the database. Lets say these Tab classes also have Histories. History class will also create its own realm instance and save itself. Will this work? :D

> I assume you mean different Realm files?

no, I meant same file. if the class is Tab the config for Realm will be `RealmConfiguration.with(schema = setOf(TabEntity::class))` or if it is History -  ` setOf(HistoryEntity::class)`. 
but anyways thanks for your answer, it was interesting.

**Comment by cmelchior** [comment]
Ah okay, in that case I would highly recommend storing a single Realm instance somewhere. It can be done relatively easy though, either through dependency injection with e.g. Koin

```
val koinModule = module {
  single { RealmConfiguration(schema = setOf(Person::class)) }
  single { Realm.open(get()) }
}
```


 or just by having a single top-level global variable:

```
val realm: Realm = Realm.open(config) by lazy()
```

**Comment by shalva97** [comment]
got it, thanks
