### ISSUE TITLE
Support one to many relation

### ISSUE THREAD

**Issue by tarasmorskyi-mediamonks** [realm/realm-kotlin#632]
When trying to support relations to the same object I receive exception about this object existing in the database on 2nd relation. Example:

```
class Product{
var children: RealmList<Product> = RealmList()
}

fun main() {
  val a = Product()
  val b = Product()
  val c = Product()
  a.children.add(c)
  b.children.add(c)
  realm.write{
   copyToRealm(a)
   copyToRealm(b)
   copyToRealm(c) //this one is optional or can be moved up as it's not copyOrUpdateToRealm()
  }
}
```

**Comment by rorbech** [comment]
Hi @tarasmorskyi-mediamonks. We have a separate issue for `copyToRealmOrUpdate` in #564. But, since the below test works and doesn't throw, can you be a bit more elaborate on your issue. Especially, what you are trying to achieve, what you would expect and the stacktraces for the exceptions you are seeing. `RealmList` is not instantiated directly anymore ... maybe try with the latest version `0.8.0` and provide the above details.

```
    class Product : io.realm.RealmObject {
        var children: io.realm.RealmList<Product> = io.realm.realmListOf<Product>()
    }

    @Test
    fun test() {
        val a = Product()
        val b = Product()
        val c = Product()
        a.children.add(c)
        b.children.add(c)
        realm.writeBlocking{
            copyToRealm(a)
            copyToRealm(b)
            copyToRealm(c)
        }
    }
```

**Comment by bmunkholm** [comment]
Closing as no further information has been provided. Feel free to ping here in case more information becomes available.
